### ISSUE TITLE
suitable mitogen module error

### ISSUE THREAD

**Issue by zhimingzhang123** [seantis/suitable#29] opened 2019-08-06 08:57 UTC
`ENV`
```python
CentOS Linux release 7.6.1810 (Core)
python3.6

ansible (2.7.12)
mitogen (0.2.7)
suitable (0.16.0)
```
According to the document, I write the following test code
```python
from suitable import Api
Api('192.168.68.134').command('whoami')    # OK

from suitable.mitogen import Api
Api('192.168.68.134').command('whoami')  # ERROR
```
ERROR
`ModuleError: Error running 'command: whoami' on 192.168.68.134
Message: Unexpected failure during module execution.
Stdout:`

who can help me, thanks.

**Comment by href** [comment] 2019-08-06 09:11
Thanks for your report!

There's not too much information why Mitogen fails here. Can you get more output by doing the following?

```python
import mitogen.utils
from suitable.mitogen import Api

mitogen.utils.log_to_file(level='DEBUG')
Api('192.168.68.134').command('whoami')
```

Also, is it possible that you are running this in a Python CLI? There is an open issue with Mitogen, which doesn't seem to work through a Python CLI together with Suitable at the moment:

https://github.com/dw/mitogen/issues/586

**Comment by zhimingzhang123** [comment] 2019-08-06 09:32
@href  this is error log, I don't seem to understand
```python
17:26:10.795769 I suitable: running - command: whoami
17:26:11.374783 D suitable: took 0:00:00.578762 to complete
17:26:11.375003 E suitable: command: whoami failed on 192.168.68.134
17:26:11.375864 D suitable: ansible-output =>
{'_ansible_no_log': False,
 'exception': 'Traceback (most recent call last):\n'
              '  File '
              '"/usr/lib/python3.6/site-packages/ansible/executor/task_executor.py", '
              'line 140, in run\n'
              '    res = self._execute()\n'
              '  File '
              '"/usr/lib/python3.6/site-packages/ansible/executor/task_executor.py", '
              'line 612, in _execute\n'
              '    result = self._handler.run(task_vars=variables)\n'
              '  File '
              '"/usr/lib/python3.6/site-packages/ansible_mitogen/mixins.py", '
              'line 116, in run\n'
              '    return super(ActionModuleMixin, self).run(tmp, task_vars)\n'
              '  File '
              '"/usr/lib/python3.6/site-packages/ansible/plugins/action/command.py", '
              'line 24, in run\n'
              '    results = merge_hash(results, '
              'self._execute_module(task_vars=task_vars, '
              'wrap_async=wrap_async))\n'
              '  File '
              '"/usr/lib/python3.6/site-packages/ansible_mitogen/mixins.py", '
              'line 354, in _execute_module\n'
              '    self._temp_file_gibberish(module_args, wrap_async)\n'
              '  File '
              '"/usr/lib/python3.6/site-packages/ansible_mitogen/mixins.py", '
              'line 333, in _temp_file_gibberish\n'
              '    self._connection.get_good_temp_dir()\n'
              '  File '
              '"/usr/lib/python3.6/site-packages/ansible_mitogen/connection.py", '
              'line 723, in get_good_temp_dir\n'
              '    self._connect()\n'
              '  File '
              '"/usr/lib/python3.6/site-packages/ansible_mitogen/connection.py", '
              'line 742, in _connect\n'
              '    self._connect_stack(stack)\n'
              '  File '
              '"/usr/lib/python3.6/site-packages/ansible_mitogen/connection.py", '
              'line 696, in _connect_stack\n'
              '    stack=mitogen.utils.cast(list(stack)),\n'
              '  File "/usr/lib/python3.6/site-packages/mitogen/core.py", line '
              '1859, in call_service\n'
              '    return recv.get().unpickle()\n'
              '  File "/usr/lib/python3.6/site-packages/mitogen/core.py", line '
              '835, in unpickle\n'
              '    raise obj\n'
              'mitogen.core.CallError: exceptions.ImportError: The Mitogen '
              "master process was unable to serve u'ansible_mitogen.target'. "
              'It may be a native Python extension, or it may be missing '
              'entirely. Check the importer debug logs on the master for more '
              'information.\n'
              '  File "<stdin>", line 3099, in _dispatch_one\n'
              '  File "<stdin>", line 3086, in _parse_request\n'
              '  File "<stdin>", line 596, in import_module\n'
              '  File "<stdin>", line 1330, in load_module\n'
              '\n',
 'msg': 'Unexpected failure during module execution.',
 'stdout': ''}
17:26:11.376022 E suitable: ignoring further calls to 192.168.68.134
```
By the way, I just created a new machine, use python2 install ansible,
```python
from suitable.mitogen import Api
Api('192.168.68.135').command('whoami') # OK
```
I am very confused

**Comment by href** [comment] 2019-08-06 09:48
This is the same error as this one: https://github.com/dw/mitogen/issues/586

If you store your script in a file (`test.py`) and run it, it should work: `python test.py`. The problem is that there's an error if you type this code into the shell when you run `python`.

**Comment by zhimingzhang123** [comment] 2019-08-06 09:53
yes, you are right. Thanks for your help.

**Comment by href** [comment] 2019-08-09 11:14
This has been fixed upstream. I'll close the ticket once Mitogen 0.2.8 is out on PyPI.

**Comment by href** [comment] 2019-08-19 06:28
This has been fixed with the latest Suitable release.

**Closed by href** 2019-08-19 06:28 UTC
