### ISSUE TITLE
getting a logging error even though the plays run correctly 

### ISSUE THREAD

**Issue by saargrincr** [seantis/suitable#40] opened 2019-12-30 09:36 UTC
The playbook runs correctly but this error still appears 

code:
---------

#!/usr/bin/env python3

from suitable import Api

api = Api ('xxxx',remote_user="xxx",remote_pass="xxx")
res = api.file(path="/tmp/test.txt",owner="root",mode='0644',state='touch')
print (res.success())

----------

error:

-- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 580, in format
    s = self.formatMessage(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 549, in formatMessage
    return self._style.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'user'
Call stack:
  File "1t.py", line 7, in <module>
    res = api.file(path="/tmp/test.txt",owner="root",mode='0644',state='touch')
  File "/usr/local/lib/python3.6/site-packages/suitable/module_runner.py", line 194, in execute
    module_args=module_args
Message: "running - file: {'path': '/tmp/test.txt', 'owner': 'root', 'mode': '0644', 'state': 'touch'}"
Arguments: ()

**Comment by href** [comment] 2020-01-14 10:02
This looks to me like an Ansible problem. I don't see it on my side, but it seems to be an instance of this: https://stackoverflow.com/a/59361033/138103

**Comment by Daverball** [comment] 2024-09-03 07:44
Since this was confirmed to be an Ansible bug that has long since then been fixed and we no longer support the Ansible version where this was broken, I will close this.

**Closed by Daverball** 2024-09-03 07:44 UTC
